# Colors (Gruvbox Light)

import = [
    "~/.config/alacritty/colors/gruvbox.toml"
]

# Default colors
[colors.primary]
# hard contrast: background = '0xf9f5d7'
background = '0xfbf1c7'
# soft contrast: background = '0xf2e5bc'
foreground = '0x3c3836'
