# Colors (Gruvbox Dark)

import = [
    "~/.config/alacritty/colors/gruvbox.toml"
]

# Default colors
[colors.primary]
# hard contrast: background = '0x1d2021'
background = '0x282828'
# soft contrast: background = '0x32302f'
foreground = '0xebdbb2'
