general.import = [
    "~/.config/alacritty/colors/solarized_light.toml"
]
[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 50 }
padding = { x = 0, y = 10 }
decorations = "Buttonless"

opacity = 1
blur = true

decorations_theme_variant = "None"

resize_increments = true


[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12

[keyboard]
bindings = [
    { key = "6", mods = "Control", action = "ReceiveChar" },  # Allow C-6 for switching to the previous Vim buffer.
    { key = "Left",  mods = "Alt",     chars = "\u01bb"                      }, # Skip word left
    { key = "Right", mods = "Alt",     chars = "\u01bf"                      }, # Skip word right
    { key = "Left",  mods = "Command", chars = "\u001bOH", mode = "AppCursor" }, # Home
    { key = "Right", mods = "Command", chars = "\u001bOF", mode = "AppCursor" }, # End
    { key = "Back",  mods = "Command", chars = "\u0015"                       }, # Delete line
    { key = "Back",  mods = "Alt",     chars = "\u001b\u007f"                   }, # Delete word
]


[debug]
render_timer = false
