import = [
    "~/.config/alacritty/solarized_light.toml"
]

[window]
dimensions = { columns = 250, lines = 50 }
padding = { x = 0, y = 0 }
decorations = "Full"

opacity = 0.95

decorations_theme_variant = "None"

resize_increments = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12

[keyboard]
bindings = [
    { key = "6", mods = "Control", action = "ReceiveChar" }  # Allow C-6 for switching to the previous Vim buffer.
]


[debug]
render_timer = false
